# This workflow is triggered by a comment on a pull request. The comment must contain "/test <command>" to trigger the workflow.

# Attribution for a bunch of this goes to CloudPosse
# https://github.com/cloudposse/actions/blob/master/.github/workflows/test-command.yml

name: test-command

on:
  repository_dispatch:
    types: [test-command]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/build-harness

permissions:
  id-token: write
  contents: read

defaults:
  run:
    # We need -e -o pipefail for consistency with GitHub Actions' default behavior
    shell: bash -e -o pipefail {0}

jobs:
  # Update the comment that triggered the /test command to show the run url
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.client_payload.pull_request.head.ref || github.ref_name }}
      - name: Update Comment
        uses: ./.github/actions/comment
        with:
          application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
          application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}

  test-all:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          platform:
          - linux/amd64
          - linux/arm64/v8
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.client_payload.pull_request.head.ref || github.ref_name }}
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
          application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}
          PLATFORM: ${{ matrix.platform }}
          github-context: test-all (${{ matrix.platform }})
          registry: ${{ env.REGISTRY }}
          image-name: ${{ env.IMAGE_NAME }}

